### ISSUE TITLE
A question about the code

### ISSUE THREAD

**Issue by t109598002** [micmic123/QmapCompression#2]
Hi, I'm interested in this work, I'd like to ask a questions.
You mentioned the quantizer component in the paper.
Where is the quantizer component in this code?
Thank's very much!

**Comment by micmic123** [comment]
Sorry for late reply.
You can refer to here:
https://github.com/micmic123/QmapCompression/blob/d719568cb75f2390dee78bc9f5eec03ec19531ce/models/entropy_models.py#L665-L667
https://github.com/micmic123/QmapCompression/blob/d719568cb75f2390dee78bc9f5eec03ec19531ce/models/entropy_models.py#L120-L148
